import { ReactElement } from "react"
import Icons from "../Icons"
import React from "react"
import Generators, { EntropicAccelerator } from "./Generators"
import { StateType } from "../App"
import { where } from "../Helpers"

// ----------------------------------------------------------------------------
// Models

export type TechnologyModel = {
  name: string
  icon: ReactElement,
  description: string | ReactElement

  cost: number,
  bought: boolean,

  effect: (state: StateType) => void,
  effectMessage: ReactElement,

  isLocked: Boolean,
  unlock?: (state: StateType) => boolean,
  lockedMessage?: string,
}

export const ProtonDecayAccelerator = {
  name: "Proton Decay Accelerator",
  icon: <Icons.Disintegration width={64} height={64} fill="white" stroke="black" strokeWidth={3} />,
  description: <div>
    <p>In a secret underground laboratory, a team of brilliant scientists has constructed a colossal machine capable of manipulating the fundamental forces of nature. This awe-inspiring device, known as the Proton Decay Accelerator, harnesses the power of exotic particles and intense energy fields to induce proton decay, a process that was once thought to be impossible.</p>

    <p>The Accelerator consists of a massive circular chamber, lined with powerful electromagnets and crisscrossed by a network of particle beams. Protons are injected into the chamber and accelerated to near-light speeds, their kinetic energy converted into a cascade of exotic particles. These particles, in turn, interact with the protons, triggering a process of forced proton decay.</p>

    <p>As the protons break down, they release a burst of energy and subatomic particles, which are carefully monitored and studied by the scientists. The Accelerator's ability to induce proton decay has opened up new realms of scientific exploration, allowing researchers to delve deeper into the mysteries of the universe and the fundamental forces that govern it.</p>

    <p>However, the Proton Decay Accelerator is not without its risks. The intense energy fields and exotic particles generated by the machine are highly unstable and potentially dangerous, requiring the utmost care and precision in its operation. Despite these challenges, the scientists remain undaunted, driven by their thirst for knowledge and the promise of unlocking the secrets of the cosmos.</p>
  </div>,

  cost: 1e3,
  bought: false,

  effect: (state: StateType) => {
    for (const generator of state.generators) {
      generator.bonuses.push({
        name: "Proton Decay Accelerator",
        multiplier: 1.05, // 5%
      })
    }
  },
  effectMessage: <span>All generator <span style={{ color: "lime" }}>+5%</span></span>,

  isLocked: true,
  unlock: (state: StateType) => (where(state.generators, (generator) => generator.name == EntropicAccelerator.name)?.owned ?? 0) >= 2,
  lockedMessage: "Requires 2 Entropic Accelerators",
}

// ----------------------------------------------------------------------------
// Models List

const Technologies: TechnologyModel[] = [
  ProtonDecayAccelerator,
];

export default Technologies;
